config/routes.rb
Rails.application.routes.draw do

  resources :rotas

  get "admin" => "rotas#admin"

  get 'percursos/:id', to: 'percursos#show', :defaults => { :format => :json }, as: :percurso
  match "percursos" => "percursos#create", :via => :post, :as => :create_percurso
  match "percursos/:id" => "percursos#update", :defaults => { :format => :json }, :via => :patch, :as => :update_percurso

  root "rotas#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/percurso.rb
class Percurso < ApplicationRecord

  serialize :partida, Array
  serialize :destino, Array
  serialize :waypoints, Array

end

app/models/rota.rb
class Rota < ApplicationRecord

  has_one :percurso

  def self.tipos_veiculos_permitidos
    %w(van ônibus)
  end

  validates :nome, presence: true

  validates :tipo_veiculo, inclusion: { in: self.tipos_veiculos_permitidos,
    message: "%{value} deve ser 'van' ou 'ônibus'" }

  validates :partida, format: { with: /\A[0-2][0-9]:[0-5][0-9]\z/,
    message: "deve estar no formato hh:mm" }



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/percursos_controller.rb
class PercursosController < ApplicationController

  before_action :set_percurso, only: [:show, :update]
  skip_before_action :verify_authenticity_token

  before_action :authenticate

  # POST /percursos
  def create
    @percurso = Percurso.new()

    respond_to do |format|
      if @percurso.save
        format.json { render :show, status: :created, location: @percurso }
      else
        format.json { render json: @percurso.errors, status: :unprocessable_entity }
    end
  end
  end

  # GET /percursos/1
  def show
  end

  # PATCH/PUT /rotas/1
  def update
    respond_to do |format|
      if update_rota
        if @percurso.update(percurso_params)
          format.json { render :show, status: :ok, location: @percurso }
        else
          format.json { render json: @percurso.errors, status: :unprocessable_entity }
        end  
      else
        rota_id = params[:percurso][:rota_id]
        format.json { render json: "Rota #{rota_id} inexistente", status: :unprocessable_entity }
      end
    end
  end

  protected
    def authenticate
      authenticate_or_request_with_http_token do |token, options|
        token == Rails.configuration.community_token
      end
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_percurso
      @percurso = Percurso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def percurso_params
      # não funciona porque waypoints é array de arrays
      #params.require(:percurso).permit(:rota_id, :partida  => [], :destino => [], :waypoints => [])
      params.require(:percurso).permit!
      # https://medium.com/@apneadiving/why-i-do-not-use-strong-parameters-in-rails-e3bd07fcda1d
      params.require(:percurso).slice('partida', 'destino', 'waypoints', 'rota_id')
    end

    def update_rota
      rota_id = params[:percurso][:rota_id]
      if rota_id
        rota =  Rota.find_by_id(rota_id)
        # Obs: Rota.find_by_id(rota_id) retorna nil se rota não existir.
        # Já Rota.find(rota_id) joga uma exceção se rota não existir.
        if rota
          rota.update(percurso: @percurso)
        else
          return false
        end
      end
      return true
    end

end

app/controllers/rotas_controller.rb
class RotasController < ApplicationController

  before_action :set_rota, only: [:show, :edit, :update, :destroy]

  http_basic_authenticate_with name: "admin",
    password: Rails.configuration.admin_password, except: [:index, :show]

  # GET /admin
  # Autentica e joga para /rotas
  def admin
    redirect_to rotas_path
  end

  # GET /rotas
  # GET /rotas.json
  def index
    @rotas = Rota.all
    respond_to do |format|
      format.html {}
      format.json { render json: @rotas, :except => [:created_at, :updated_at] }
    end
  end

  # GET /rotas/1
  # GET /rotas/1.json
  def show
    @google_maps_key = Rails.configuration.google_maps_key
    respond_to do |format|
      format.html {}
      format.json { render json: @rota, :except => [:created_at, :updated_at] }
    end
  end

  # GET /rotas/new
  def new
    @rota = Rota.new
  end

  # GET /rotas/1/edit
  def edit
  end

  # POST /rotas
  # POST /rotas.json
  def create
    @rota = Rota.new(rota_params)

    respond_to do |format|
      if @rota.save
        format.html { redirect_to @rota, notice: 'Rota was successfully created.' }
        format.json { render :show, status: :created, location: @rota }
      else
        format.html { render :new }
        format.json { render json: @rota.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rotas/1
  # PATCH/PUT /rotas/1.json
  def update
    respond_to do |format|
      if @rota.update(rota_params)
        format.html { redirect_to @rota, notice: 'Rota was successfully updated.' }
        format.json { render :show, status: :ok, location: @rota }
      else
        format.html { render :edit }
        format.json { render json: @rota.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rotas/1
  # DELETE /rotas/1.json
  def destroy
    @rota.destroy
    respond_to do |format|
      format.html { redirect_to rotas_url, notice: 'Rota was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rota
      @rota = Rota.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rota_params
      params.require(:rota).permit(:nome, :partida, :tipo_veiculo)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def logged_in?
    not request.authorization.nil?
  end

end

app/helpers/percursos_helper.rb
module PercursosHelper
end

app/helpers/rotas_helper.rb
module RotasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rotas</title>
    <!-- TODO: reabilitar logo -->
    <!--link rel=icon href=rotas-small.png sizes="16x16" type="image/png"-->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rotas/_form.html.erb
<%= form_with(model: rota, local: true) do |form| %>
  <% if rota.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rota.errors.count, "error") %> prohibited this rota from being saved:</h2>

      <ul>
      <% rota.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :partida %>
    <%= form.text_field :partida %>
  </div>

  <div class="field">
    <%= form.label :tipo_veiculo %>
    <%= form.select(:tipo_veiculo,
      options_for_select(Rota.tipos_veiculos_permitidos,
      rota.tipo_veiculo))%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rotas/edit.html.erb
<h1>Editando Rota</h1>

<%= render 'form', rota: @rota %>

<%= link_to 'Voltar', rotas_path %>

app/views/rotas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rotas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Partida</th>
      <th>Tipo veiculo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rotas.each do |rota| %>
      <tr>
        <td><%= rota.nome %></td>
        <td><%= rota.partida %></td>
        <td><%= rota.tipo_veiculo %></td>
        <td><%= link_to 'Mostrar no mapa', rota %></td>
        <% if logged_in? %>
          <td><%= link_to 'Editar', edit_rota_path(rota) %> </td>
          <td><%= link_to 'Excluir', rota, method: :delete, data: { confirm: 'Você está certo disso?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if logged_in? %>
  <%= link_to 'Nova Rota', new_rota_path %>
<% end %>

app/views/rotas/new.html.erb
<h1>Nova Rota</h1>

<%= render 'form', rota: @rota %>

<%= link_to 'Voltar', rotas_path %>

app/views/rotas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @rota.nome %>
</p>

<p>
  <strong>Partida:</strong>
  <%= @rota.partida %>
</p>

<p>
  <strong>Tipo veiculo:</strong>
  <%= @rota.tipo_veiculo %>
</p>

<div id="map">Carregando mapa...</div>

<% if logged_in? %>
  <%= link_to 'Editar', edit_rota_path(@rota) %> |
<% end %>
<%= link_to 'Voltar', rotas_path %>

<% if @rota.percurso %>

  <style>
    #map {
      height: 400px;
      width: 80%;
     }
  </style>

  <script>
    function initMap() {
        showRotaOnMaps(<%= @rota.percurso.partida %>,
                       <%= @rota.percurso.destino %>,
                       <%=raw @rota.percurso.waypoints %>);
    }
  </script>

  <script async defer
  src="https://maps.googleapis.com/maps/api/js?key=<%=@google_maps_key%>&callback=initMap">
  </script>

<% else %>
  <script>
      $('#map').html('Mapa indisponível, percurso ainda não cadastrado');
  </script>
<% end %>